Some updates

diff --git a/automaticGitSyncing b/automaticGitSyncing
--- a/automaticGitSyncing
+++ b/automaticGitSyncing
@@ -1,19 +1,21 @@
-#/bin/bash
+#!/bin/bash
 ##AUTHORS: koen-github, swiftgame##
+
+# swiftgame@&y2015.06.13.20:14:40&: MAIN_DIR can probably be deleted, clones know what the main git repo dir is.
 
 CONFIG_FILE=$1
 COMMIT_TEXT=$2
-EXTERNAL_SERVERS=$3
+MOUNT_EXTERNAL_SERVERS=$3
 VERSION="1.0.0"
 if [[ $CONFIG_FILE == "" ]]
 then
-echo 'Usage: auto_sync_git [CONFIG_FILE] [GIT_COMMIT_TEXT] [EXTERNAL_SERVER/YES/NO]
+echo 'Usage: auto_sync_git [CONFIG_FILE] [GIT_COMMIT_TEXT] [MOUNT_EXTERNAL_SERVERS/YES/NO]
 This program can be used to automatically sync git repositories. 
-Use if you do not want any usefull git commit text, and just want to sync all your repos
+Use if you do not want any useful git commit text, and just want to sync all your repos.
 
 Note: Config_file must only have root access, or this script can not run
 
-========CONFIG_FILE========
+========EXAMPLE CONFIG_FILE========
 export MAIN_DIR="/home/koen/gitTestRepo/mainGit"
 declare CLONE_DIRS=("/home/koen/gitTestRepo/alltheclones/clone1/mainGit" "/home/koen/gitTestRepo/alltheclones/clone2/mainGit" "/home/koen/gitTestRepo/alltheclones/clone3/mainGit" "/home/koen/gitTestRepo/alltheclones/clone4/mainGit")
 declare EXT_SERVERS=("user@host:git/server/dir/")
@@ -26,50 +28,48 @@ else
 
 FILE_PERMISSION=`stat -c %A  $CONFIG_FILE`
 FILE_OWNER=`stat -c %U  $CONFIG_FILE`
+
 if [[ $FILE_OWNER == "root" ]]
 then
-if [[ $FILE_PERMISSION == "-rw-r--r--" ]]
-then
-FILE_CONTENTS=`cat $CONFIG_FILE`
-##NOT SAFE, FIND A BETTER WAY TO DO THIS
-eval $FILE_CONTENTS
-else
+   if [[ $FILE_PERMISSION == "-rw-r--r--" ]]
+   then
+      FILE_CONTENTS=`cat $CONFIG_FILE`
+      ##NOT SAFE, FIND A BETTER WAY TO DO THIS
+      eval $FILE_CONTENTS
+      else
 
-echo "Config file has to the right permission, must been set to: -rw-r--r--"
-exit 1;
-fi
-else
-echo "Config file is not from root"
-exit 1;
-fi
-
-
+      echo "Config file has to the right permission, must been set to: -rw-r--r--"
+      exit 1;
+      fi
+      else
+      echo "Config file is not from root"
+      exit 1;
+   fi
 fi
 
 echo "GIVEN ARGUMENTS: "
 echo "CONFIG_FILE: $CONFIG_FILE"
 echo "GIT_COMMIT_TEXT: $COMMIT_TEXT"
-echo "EXTERNAL_SERVER: $EXTERNAL_SERVERS"
+echo "EXTERNAL_SERVER: $MOUNT_EXTERNAL_SERVERS"
 
 
 iterator=0
-if [[ $EXTERNAL_SERVERS == "YES" ]]
+if [[ $MOUNT_EXTERNAL_SERVERS == "YES" ]]
 then
 
 echo "MOUNTING EXTERNALS SERVERS"
 
 for i in "${EXT_SERVERS[@]}"
 do
-	sudo sshfs $i ${MOUNTPOINTS[$iterator]}
-	EXIT_CODE=`echo $?`
-	   if [[ $EXIT_CODE == 1 ]] #is a mountpoint 
-	    then
-		echo "Couldn't mount server $i to mountpoint ${MOUNTPOINTS[$iterator]}"
-		exit 1
-	    fi
+   sudo sshfs $i ${MOUNTPOINTS[$iterator]}
+   EXIT_CODE=`echo $?`
+      if [[ $EXIT_CODE == 1 ]] #is a mountpoint 
+      then
+         echo "Couldn't mount server $i to mountpoint ${MOUNTPOINTS[$iterator]}"
+	 exit 1
+      fi
 
-	((iterator++))
-
+      ((iterator++))
 done
 
 fi
